### ISSUE TITLE
Reference file type

### ISSUE THREAD

**Issue by kwonej0617** [zhongzhd/ont_m6a_detection#1]
Hi, Thank you for providing scripts to run m6a detection tools.
I am a little bit confused to choose a reference file between the reference "genome" and "transcriptome".
Looking at m6A detection tools you provided in github, it says to use reference transcriptome. How would the result be different if I use a reference genome?

I am looking forward to hearing from you!

Thank you!

**Comment by zhongzhd** [comment]
there is no difference, but it is worth noting that some tools do not support the reference "genome".

**Comment by kwonej0617** [comment]
Thank you @zhongzhd for your reply. 

In the nanopolish documentation, when it mentions a reference, it says reference genome. However, I saw that in the documentation of some m6a detection tools, they used reference transcriptome. Did you use reference transcriptome for nanopolish step? 

Also, I have a question about having `--reverse_sequence true `in the base-calling process.
I am wondering if it is necessary to have the option when performing the base-calling using RNA sequencing data even though I specified flow cell and kit number. Because the flow cell and kit are separated depending on either DNA or RNA sequencing, I thought I didn't have to do so. 
However, for example, the base-calling command line in nanocompore documentation includes the option. However, your pre-processing script and if I remember correctly, xPore didn't specify it.
![image](https://github.com/zhongzhd/ont_m6a_detection/assets/80375662/7b4b7cf3-54a9-482f-8529-5f183742eb0c)

**Comment by zhongzhd** [comment]
Firstly, I apologize for not being able to reply to you in a timely manner due to my recent busy schedule.
In fact, we used reference transcriptome for nanopolish step.
And for the basecalling step, you can just specify a basic configuration file, like "rna_r9.4.1_70bps_hac.cfg".
For the reference files, i don't  know what species you're testing for. And if you encounter a error message while running a tool, you can try searching for similar issue under the corresponding tool's github.
