### ISSUE TITLE
coordinate transformation issue

### ISSUE THREAD

**Issue by acarmas1** [zhongzhd/ont_m6a_detection#3]
Hello,

I'm interested in using your tool for coordinate transformation. I've identified m6A sites using m6Anet, and now I want to see its distribution in the 3'utr cds and 5'utr. Therefore, after running your single_tools.sh and finish the loop, my chr0.bed files are empty. Therefore, I don't know if it is because I'm setting my bed variable (bed=path_to_genome_transcriptome_coordinate) wrong. I tried giving the path of my reference genome.fna, annotations in .gtf and .gff format and converting my .gff file into .bed and setting these as input, and nothing worked.

On this email, I uploaded my inputs, outputs, and scripts used: https://1drv.ms/f/s!AokqkR3muxL0jvIA6z2EICcYp3_L-w?e=HrT43L

Please if you can help me to troubleshoot this. I'll appreciate it. 

I'm looking forward to hearing from you.

Best,
Camila

**Comment by zhongzhd** [comment]
Firstly, I apologize for not being able to reply to you in a timely manner due to my recent busy schedule.
For the "bed=path_to_genome_transcriptome_coordinate", you should ensure that it is in the format shown in the following image.
<img width="229" alt="image" src="https://github.com/zhongzhd/ont_m6a_detection/assets/71424789/df5a1eeb-334a-4b1e-94b9-6d03267f31b6">

**Comment by kwonej0617** [comment]
Hi, @zhongzhd 

I was wondering what the position represents in the bed format. Also, could you tell me how you generated the bed file, or do have a script to generate the file? 

Thank you so much for your help!

**Comment by kwonej0617** [comment]
Hi, @acarmas1 
I reached out to the author for this issue. He said because he was not able to log in the GitHub for some reason, I am sharing what I got from the author as follows.

" Regarding the issue itself, you can use metaPlotR (https://github.com/olarerin/metaPlotR) to get the bed file you want. You can use make_annot_bed.pl from metaPlotR creates a master annotation file (bed format) of every nucleotide in the transcriptome similar to the picture below, then you can easily convert it into the "bed=path_to_genome_transcriptome_coordinate" with awk tools."
