### ISSUE TITLE
Coordinate transformation issue

### ISSUE THREAD

**Issue by SEVEN-XYCHEN** [zhongzhd/ont_m6a_detection#5]
Hello，
The result obtained by the MINES software is the location coordinate of the Transcriptome. How should I convert it into the location coordinate of the corresponding genome?
That is to say, how to obtain the bed file below？

![1687701382336(1)](https://github.com/zhongzhd/ont_m6a_detection/assets/87250947/5a1c44a0-4960-461f-9a7e-881808f838f2)
Best,
Chen

**Comment by kwonej0617** [comment]
@SEVEN-XYCHEN 

I reached out to the author for this issue. He said because he was not able to log in the GitHub for some reason, I am sharing what I got from the author as follows. 

" Regarding the issue itself, you can use metaPlotR (https://github.com/olarerin/metaPlotR) to get the bed file you want. You can use **make\_annot\_bed.pl** from metaPlotR creates a master annotation file (bed format) of every nucleotide in the transcriptome similar to the picture below, then you can easily convert it into the "bed=path_to_genome_transcriptome_coordinate" with awk tools."

**Comment by SEVEN-XYCHEN** [comment]
Thank you very much for your help! Best, Chen
